# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ae78cd3f427595718581efd32716d564289f35460bb0f603e8a4f25df99349d12d7c12e401ed7e8bcadc5dd4f0921eb2cacaf186074c15f8cfcf0bbdaf331d1

test:
  secret_key_base: fd83942d591ef30ac854e3376b536d0377db036a8bd1e175004debca2b825dc15402c812ed2992108e9d04f58dcf8c6843f7ed60f2f62827f2b8fabb84557495

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
